name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: chess_mate.settings
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      STRIPE_PUBLIC_KEY: ${{ secrets.STRIPE_PUBLIC_KEY }}
      DEBUG: True
      SECRET_KEY: test-key-for-ci
      DATABASE_URL: sqlite:///test_db.sqlite3

    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-django pytest-cov

    - name: Setup test environment
      run: |
        cd chess_mate
        python manage.py makemigrations
        python manage.py migrate
        python manage.py check

    - name: Run tests
      run: |
        cd chess_mate
        python -m pytest --cov=./ --cov-report=xml core/tests/

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        file: ./chess_mate/coverage.xml
        fail_ci_if_error: true 